application: hello2
version: 1
runtime: go
api_version: go1

handlers:
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  expiration: "1d"
  mime_type: image/x-icon

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt
  expiration: "1d"

- url: /static
  static_dir: static
  expiration: "1h"

- url: /.*
  script: _go_app

admin_console:
  pages:
  - name: App stats
    url: /_ah/stats/
